name: CD

on:
  push:
    branches: [main]  
    paths:
    - "src/**/**"
    - "tests/**/**"
    - ".github/**/**"
  
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: KellysonRN/azure-webapp-labs/.github/workflows/ci.yaml@main

  dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: publish-api-zip
        path: .

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZ_PUB_PROFILE }}
        package: ./publish.zip

  acc:
    needs: dev
    runs-on: ubuntu-latest
    environment: acc

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: publish-api-zip
        path: .

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZ_PUB_PROFILE }}
        package: ./publish.zip